#include <exec/types.h>
#include <libraries/dos.h>
#include <proto/dos.h>
#include <string.h>
#include "config.h"
#define CONF_NAME "ISSTracker.conf"
static LONG parse_num(const char *s, WORD *out){ LONG sign; LONG v; sign=1; v=0; if(*s=='-'){ sign=-1; s++; } while(*s>='0' && *s<='9'){ v=v*10+(*s-'0'); s++; } v*=sign; if(v<-32768L || v>32767L) return -1; *out=(WORD)v; return 0; }
static int starts(const char *s,const char *k){ while(*k){ if(*s++!=*k++) return 0; } return 1; }
static void copy_cfg_str(char *dst, UWORD max, const char *src){ UWORD i; if(max==0) return; for(i=0;i+1<max && src[i] && src[i]!='\n' && src[i]!='\r';i++) dst[i]=src[i]; dst[i]=0; }
static void write_str(BPTR fh,const char *s){ LONG n; n=0; while(s[n]) n++; Write(fh,(APTR)s,n); }
static void write_num(BPTR fh,LONG n){ char buf[14]; char tmp[12]; WORD i; WORD p; if(n<0){ write_str(fh,"-"); n=-n; } i=0; do{ tmp[i++]=(char)('0'+(n%10)); n/=10; }while(n && i<11); p=0; while(i>0) buf[p++]=tmp[--i]; buf[p]=0; write_str(fh,buf); }
void config_defaults(IssTrackerApp *app){ app->win_left=20; app->win_top=20; app->win_width=640; app->win_height=300; app->update_interval_min=2; app->language=ISS_LANG_DE; app->pen_water=4; app->pen_land=7; app->pen_border=1; app->pen_marker=2; app->pen_marker_fill=3; app->pen_trail=5; app->pen_text=1; app->pen_panel_bg=0; strcpy(app->font_name,"topaz.font"); app->font_size=8; app->ui_font=0; }
void config_load(IssTrackerApp *app){ BPTR fh; char buf[1024]; LONG got; UWORD i; UWORD line; WORD val; fh=Open((STRPTR)CONF_NAME,MODE_OLDFILE); if(!fh) return; got=Read(fh,buf,sizeof(buf)-1); Close(fh); if(got<=0) return; buf[got]=0; line=0; for(i=0;i<=(UWORD)got;i++){ if(buf[i]=='\n' || buf[i]=='\r' || buf[i]==0){ char old; old=buf[i]; buf[i]=0; if(starts(&buf[line],"left=") && parse_num(&buf[line+5],&val)==0) app->win_left=val; else if(starts(&buf[line],"top=") && parse_num(&buf[line+4],&val)==0) app->win_top=val; else if(starts(&buf[line],"width=") && parse_num(&buf[line+6],&val)==0) app->win_width=val; else if(starts(&buf[line],"height=") && parse_num(&buf[line+7],&val)==0) app->win_height=val; else if(starts(&buf[line],"update_interval=") && parse_num(&buf[line+16],&val)==0) app->update_interval_min=(UWORD)val; else if(starts(&buf[line],"language=") && parse_num(&buf[line+9],&val)==0) app->language=(UBYTE)val; else if(starts(&buf[line],"font_name=")) copy_cfg_str(app->font_name,sizeof(app->font_name),&buf[line+10]); else if(starts(&buf[line],"font_size=") && parse_num(&buf[line+10],&val)==0) app->font_size=(UWORD)val; else if(starts(&buf[line],"pen_water=") && parse_num(&buf[line+10],&val)==0) app->pen_water=(UBYTE)val; else if(starts(&buf[line],"pen_land=") && parse_num(&buf[line+9],&val)==0) app->pen_land=(UBYTE)val; else if(starts(&buf[line],"pen_border=") && parse_num(&buf[line+11],&val)==0) app->pen_border=(UBYTE)val; else if(starts(&buf[line],"pen_marker=") && parse_num(&buf[line+11],&val)==0) app->pen_marker=(UBYTE)val; else if(starts(&buf[line],"pen_marker_fill=") && parse_num(&buf[line+16],&val)==0) app->pen_marker_fill=(UBYTE)val; else if(starts(&buf[line],"pen_trail=") && parse_num(&buf[line+10],&val)==0) app->pen_trail=(UBYTE)val; else if(starts(&buf[line],"pen_text=") && parse_num(&buf[line+9],&val)==0) app->pen_text=(UBYTE)val; else if(starts(&buf[line],"pen_panel_bg=") && parse_num(&buf[line+13],&val)==0) app->pen_panel_bg=(UBYTE)val; buf[i]=old; while(i+1<=(UWORD)got && (buf[i+1]=='\n' || buf[i+1]=='\r')) i++; line=(UWORD)(i+1); } } if(app->win_width<320) app->win_width=320; if(app->win_height<190) app->win_height=190; if(app->win_width>640) app->win_width=640; if(app->win_height>512) app->win_height=512; if(app->update_interval_min<2) app->update_interval_min=2; if(app->update_interval_min>120) app->update_interval_min=120; if(app->language>ISS_LANG_PL) app->language=ISS_LANG_DE; if(app->font_name[0]==0) strcpy(app->font_name,"topaz.font"); if(app->font_size<6) app->font_size=6; if(app->font_size>32) app->font_size=32; }
void config_save(IssTrackerApp *app){ BPTR fh; fh=Open((STRPTR)CONF_NAME,MODE_NEWFILE); if(!fh) return; write_str(fh,"# ISS Tracker settings\nleft="); write_num(fh,app->win_left); write_str(fh,"\ntop="); write_num(fh,app->win_top); write_str(fh,"\nwidth="); write_num(fh,app->win_width); write_str(fh,"\nheight="); write_num(fh,app->win_height); write_str(fh,"\nupdate_interval="); write_num(fh,app->update_interval_min); write_str(fh,"\nlanguage="); write_num(fh,app->language); write_str(fh,"\nfont_name="); write_str(fh,app->font_name); write_str(fh,"\nfont_size="); write_num(fh,app->font_size); write_str(fh,"\npen_water="); write_num(fh,app->pen_water); write_str(fh,"\npen_land="); write_num(fh,app->pen_land); write_str(fh,"\npen_border="); write_num(fh,app->pen_border); write_str(fh,"\npen_marker="); write_num(fh,app->pen_marker); write_str(fh,"\npen_marker_fill="); write_num(fh,app->pen_marker_fill); write_str(fh,"\npen_trail="); write_num(fh,app->pen_trail); write_str(fh,"\npen_text="); write_num(fh,app->pen_text); write_str(fh,"\npen_panel_bg="); write_num(fh,app->pen_panel_bg); write_str(fh,"\n"); Close(fh); }
