#include <exec/types.h>
#include <libraries/dos.h>
#include <proto/dos.h>
#include "config.h"
#define CONF_NAME "ISSTracker.conf"
static LONG parse_num(const char *s, WORD *out){ LONG sign; LONG v; sign=1; v=0; if(*s=='-'){ sign=-1; s++; } while(*s>='0' && *s<='9'){ v=v*10+(*s-'0'); s++; } v*=sign; if(v<-32768L || v>32767L) return -1; *out=(WORD)v; return 0; }
static int starts(const char *s,const char *k){ while(*k){ if(*s++!=*k++) return 0; } return 1; }
static void write_str(BPTR fh,const char *s){ LONG n; n=0; while(s[n]) n++; Write(fh,(APTR)s,n); }
static void write_num(BPTR fh,LONG n){ char buf[14]; char tmp[12]; WORD i; WORD p; if(n<0){ write_str(fh,"-"); n=-n; } i=0; do{ tmp[i++]=(char)('0'+(n%10)); n/=10; }while(n && i<11); p=0; while(i>0) buf[p++]=tmp[--i]; buf[p]=0; write_str(fh,buf); }
void config_defaults(IssTrackerApp *app){ app->win_left=20; app->win_top=20; app->win_width=382; app->win_height=220; app->update_interval_min=5; }
void config_load(IssTrackerApp *app){ BPTR fh; char buf[320]; LONG got; UWORD i; UWORD line; WORD val; fh=Open((STRPTR)CONF_NAME,MODE_OLDFILE); if(!fh) return; got=Read(fh,buf,sizeof(buf)-1); Close(fh); if(got<=0) return; buf[got]=0; line=0; for(i=0;i<=(UWORD)got;i++){ if(buf[i]=='\n' || buf[i]=='\r' || buf[i]==0){ char old; old=buf[i]; buf[i]=0; if(starts(&buf[line],"left=") && parse_num(&buf[line+5],&val)==0) app->win_left=val; else if(starts(&buf[line],"top=") && parse_num(&buf[line+4],&val)==0) app->win_top=val; else if(starts(&buf[line],"width=") && parse_num(&buf[line+6],&val)==0) app->win_width=val; else if(starts(&buf[line],"height=") && parse_num(&buf[line+7],&val)==0) app->win_height=val; else if(starts(&buf[line],"update_interval=") && parse_num(&buf[line+16],&val)==0) app->update_interval_min=(UWORD)val; buf[i]=old; while(i+1<=(UWORD)got && (buf[i+1]=='\n' || buf[i+1]=='\r')) i++; line=(UWORD)(i+1); } } if(app->win_width<320) app->win_width=320; if(app->win_height<190) app->win_height=190; if(app->win_width>640) app->win_width=640; if(app->win_height>512) app->win_height=512; if(app->update_interval_min<5) app->update_interval_min=5; if(app->update_interval_min>120) app->update_interval_min=120; }
void config_save(IssTrackerApp *app){ BPTR fh; fh=Open((STRPTR)CONF_NAME,MODE_NEWFILE); if(!fh) return; write_str(fh,"# ISS Tracker settings\nleft="); write_num(fh,app->win_left); write_str(fh,"\ntop="); write_num(fh,app->win_top); write_str(fh,"\nwidth="); write_num(fh,app->win_width); write_str(fh,"\nheight="); write_num(fh,app->win_height); write_str(fh,"\nupdate_interval="); write_num(fh,app->update_interval_min); write_str(fh,"\n"); Close(fh); }
