#include "funfacts.h"
static const char *facts[] = {
"Funfact: Die ISS umrundet die Erde in etwa 90 Minuten.",
"Funfact: Astronauten auf der ISS sehen pro Tag rund 16 Sonnenaufgaenge.",
"Funfact: Die ISS fliegt mit etwa 27600 km/h um die Erde.",
"Funfact: In Schwerelosigkeit trennen sich Gas und Fluessigkeit im Magen schlechter.",
"Funfact: Raumanzuege sind kleine Raumfahrzeuge mit eigener Lebenserhaltung.",
"Funfact: Der erste Mensch im All war Juri Gagarin im Jahr 1961.",
"Funfact: Der erste Mensch auf dem Mond war Neil Armstrong im Jahr 1969.",
"Funfact: Die erste Frau im All war Walentina Tereschkowa im Jahr 1963.",
"Funfact: Die Apollo-11-Landung dauerte vom Start bis zur Landung auf dem Mond etwa vier Tage.",
"Funfact: Mondstaub ist sehr fein und kann an Raumanzuegen stark haften.",
"Funfact: Die ISS ist groesser als ein Fussballfeld, wenn man die Solarmodule mitzahlt.",
"Funfact: Auf der ISS gibt es keine Dusche wie auf der Erde.",
"Funfact: Wasser wird auf Raumstationen sehr sorgfaeltig wiederverwendet.",
"Funfact: Astronauten schlafen in Schlafsaecken, die an der Wand befestigt sind.",
"Funfact: Ohne Erdschwere kann sich die Wirbelsaeule strecken und Menschen werden etwas groesser.",
"Funfact: Muskeltraining ist im All Pflicht, damit Muskeln und Knochen stark bleiben.",
"Funfact: Die ISS wurde aus vielen Modulen im Orbit zusammengesetzt.",
"Funfact: Das Hubble-Teleskop wurde mehrfach von Astronauten im All repariert.",
"Funfact: Voyager 1 ist das am weitesten entfernte menschengemachte Objekt.",
"Funfact: Funksignale zum Mars brauchen je nach Abstand mehrere Minuten.",
"Funfact: Auf dem Mond gibt es keine dichte Atmosphaere und keinen Wind wie auf der Erde.",
"Funfact: Fussabdruecke auf dem Mond koennen sehr lange erhalten bleiben.",
"Funfact: Raketen starten meistens nach Osten, um die Erdrotation auszunutzen.",
"Funfact: Der groesste Teil einer Rakete besteht beim Start aus Treibstoff.",
"Funfact: Ein Orbit ist ein staendiges Fallen um die Erde herum.",
"Funfact: Schwerelosigkeit im Orbit entsteht, weil Raumfahrzeug und Besatzung gemeinsam fallen.",
"Funfact: Die Erde ist aus dem All als duenne blaue Atmosphaerenschicht sichtbar.",
"Funfact: Polarlichter koennen von der ISS aus sehr gut beobachtet werden.",
"Funfact: Blitze in Gewittern sind aus dem Orbit deutlich sichtbar.",
"Funfact: Die ersten Satelliten waren viel kleiner als heutige Kommunikationssatelliten.",
"Funfact: Sputnik 1 war 1957 der erste kuenstliche Satellit.",
"Funfact: GPS funktioniert mit sehr genauen Atomuhren auf Satelliten.",
"Funfact: Relativitaetseffekte muessen bei GPS korrigiert werden.",
"Funfact: Viele Erdbeobachtungssatelliten fliegen ueber die Pole.",
"Funfact: Ein geostationaerer Satellit bleibt scheinbar ueber demselben Punkt der Erde.",
"Funfact: Geostationaere Satelliten kreisen in rund 35786 km Hoehe.",
"Funfact: Die ISS fliegt deutlich niedriger als geostationaere Satelliten.",
"Funfact: Die ISS muss regelmaessig angehoben werden, weil sie langsam an Hoehe verliert.",
"Funfact: Auch in ISS-Hoehe gibt es noch winzige Reste der Atmosphaere.",
"Funfact: Kleine Triebwerkszuendungen koennen die Bahn der ISS korrigieren.",
"Funfact: Raumfahrzeuge muessen beim Andocken Geschwindigkeit und Position extrem genau treffen.",
"Funfact: Die Sojus-Kapsel landet mit Fallschirmen und Bremsraketen.",
"Funfact: Apollo-Kapseln landeten im Ozean und wurden von Schiffen geborgen.",
"Funfact: Space-Shuttle-Orbiter landeten wie Gleitflugzeuge ohne Motorleistung.",
"Funfact: Der Mars hat den groessten Vulkan des Sonnensystems: Olympus Mons.",
"Funfact: Der Mars-Tag ist nur etwa 40 Minuten laenger als ein Erdtag.",
"Funfact: Der Mond entfernt sich jedes Jahr ein kleines Stueck von der Erde.",
"Funfact: Die Venus rotiert sehr langsam und in entgegengesetzter Richtung.",
"Funfact: Ein Tag auf der Venus ist laenger als ein Venusjahr.",
"Funfact: Merkur hat trotz Sonnennaehe extrem kalte Schattenbereiche an den Polen.",
"Funfact: Jupiter ist der groesste Planet unseres Sonnensystems.",
"Funfact: Der Grosse Rote Fleck auf Jupiter ist ein riesiger Sturm.",
"Funfact: Saturns Ringe bestehen aus Eis- und Gesteinsbrocken.",
"Funfact: Uranus ist stark gekippt und rollt gewissermassen um die Sonne.",
"Funfact: Neptun hat sehr schnelle Winde in seiner Atmosphaere.",
"Funfact: Pluto wurde 2006 als Zwergplanet neu eingeordnet.",
"Funfact: Kometen bestehen aus Eis, Staub und Gestein.",
"Funfact: Ein Kometenschweif zeigt meist von der Sonne weg.",
"Funfact: Asteroiden sind Ueberreste aus der Entstehungszeit des Sonnensystems.",
"Funfact: Meteoriten sind Weltraumgestein, das den Erdboden erreicht.",
"Funfact: Sternschnuppen sind meist kleine Teilchen, die in der Atmosphaere vergluehen.",
"Funfact: Die Milchstrasse enthaelt hunderte Milliarden Sterne.",
"Funfact: Unsere Sonne ist ein Stern mittlerer Groesse.",
"Funfact: Licht von der Sonne braucht etwa acht Minuten bis zur Erde.",
"Funfact: Licht vom Mond braucht nur etwas mehr als eine Sekunde zur Erde.",
"Funfact: Radiowellen reisen im Vakuum mit Lichtgeschwindigkeit.",
"Funfact: Raumsonden nutzen oft Swing-by-Manoever, um Geschwindigkeit zu gewinnen.",
"Funfact: Bei einem Swing-by gibt ein Planet winzige Bahnenergie an eine Sonde ab.",
"Funfact: Die Cassini-Sonde erforschte viele Jahre lang Saturn und seine Monde.",
"Funfact: Die Galileo-Sonde untersuchte Jupiter und seine Monde.",
"Funfact: Die New-Horizons-Sonde flog 2015 an Pluto vorbei.",
"Funfact: Der Marsrover Curiosity landete mit einem Skycrane-System.",
"Funfact: Marsrover fahren langsam, weil Sicherheit wichtiger ist als Tempo.",
"Funfact: Solarpanels liefern vielen Raumsonden elektrische Energie.",
"Funfact: Weiter draussen im Sonnensystem werden oft Radioisotopengeneratoren genutzt.",
"Funfact: Raumfahrzeuge muessen extreme Temperaturunterschiede aushalten.",
"Funfact: Im Vakuum gibt es keine Luft, die Waerme durch Konvektion abtransportiert.",
"Funfact: Astronauten koennen im All keinen normalen Bleistiftstaub herumfliegen lassen wollen.",
"Funfact: Spezielle Stifte funktionieren in vielen Lagen und auch in Schwerelosigkeit.",
"Funfact: Essen im All wird oft so verpackt, dass keine Kruemel frei schweben.",
"Funfact: Brot wird auf Raumstationen oft durch Tortillas ersetzt, weil sie weniger kruemeln.",
"Funfact: Fluessigkeiten bilden in Schwerelosigkeit kugelige Tropfen.",
"Funfact: Feuer verhaelt sich in Schwerelosigkeit anders als auf der Erde.",
"Funfact: Flammen koennen in Schwerelosigkeit eher kugelfoermig aussehen.",
"Funfact: Astronauten trainieren Aussenbordeinsaetze oft unter Wasser.",
"Funfact: Der Neutral Buoyancy Pool der NASA ist ein riesiges Trainingsbecken.",
"Funfact: Bei einem Weltraumspaziergang bleibt ein Astronaut durch Sicherungsleinen verbunden.",
"Funfact: Raumanzug-Handschuhe sind technisch besonders anspruchsvoll.",
"Funfact: Die ISS nutzt riesige Radiatoren, um Waerme ins All abzugeben.",
"Funfact: Im All kann Waerme nur durch Strahlung wirklich abgegeben werden.",
"Funfact: Satelliten muessen vor geladenen Teilchen der Sonne geschuetzt werden.",
"Funfact: Sonnenstuerme koennen Funkverbindungen und Satelliten stoeren.",
"Funfact: Der Van-Allen-Guertel enthaelt energiereiche geladene Teilchen.",
"Funfact: Raumfahrzeuge muessen Mikrometeoriten und Weltraumschrott beruecksichtigen.",
"Funfact: Weltraumschrott wird verfolgt, damit Satelliten ausweichen koennen.",
"Funfact: Die ISS kann bei Bedarf Ausweichmanoever gegen Weltraumschrott fliegen.",
"Funfact: Viele Satelliten vergluehen am Ende ihrer Mission kontrolliert in der Atmosphaere.",
"Funfact: Manche Raumsonden werden absichtlich auf Planeten oder Monde gelenkt.",
"Funfact: Planetenschutz soll verhindern, dass irdische Mikroben andere Welten verunreinigen.",
"Funfact: Europa, ein Mond des Jupiter, besitzt wahrscheinlich einen Ozean unter Eis.",
"Funfact: Enceladus, ein Saturnmond, schleudert Eisfontaenen ins All.",
"Funfact: Titan, ein Saturnmond, hat eine dichte Atmosphaere und Seen aus Kohlenwasserstoffen.",
"Funfact: Der erste deutsche ESA-Astronaut war Ulf Merbold.",
"Funfact: Alexander Gerst verbrachte mehrere Missionen auf der ISS.",
"Funfact: Auf der ISS arbeiten meist mehrere Nationen gleichzeitig zusammen.",
"Funfact: Raumfahrtmissionen werden oft viele Jahre vor dem Start geplant.",
"Funfact: Ein Startfenster ist der Zeitraum, in dem ein Raumfahrzeug guenstig starten kann.",
};
const char *funfact_get(UWORD index){ if(index>=funfact_count()) index=0; return facts[index]; }
UWORD funfact_count(void){ return (UWORD)(sizeof(facts)/sizeof(facts[0])); }
