#include <exec/types.h>
#include <exec/libraries.h>
#include <proto/exec.h>
#include <string.h>
#include "amitcp13/bsdsocket.h"
#include "http_client.h"
#define HTTP_PORT 80
extern struct Library *SocketBase;
static struct Amitcp13BsdFdSet g_rfds;
static struct Amitcp13BsdFdSet g_wfds;
static struct Amitcp13BsdTimeVal g_tv;
static ULONG g_wait_sigs;
static int g_one;
static int g_so_error;
static int g_so_error_len;
static struct Amitcp13BsdSockAddrIn g_addr;
static int call_socket(struct Library *base, int domain, int type, int protocol){ register int d0 __asm("d0")=domain; register int d1 __asm("d1")=type; register int d2 __asm("d2")=protocol; register struct Library *a6 __asm("a6")=base; __asm volatile("jsr a6@(-30:W)" : "+r"(d0), "+r"(d1), "+r"(d2) : "r"(a6) : "a0", "a1", "cc", "memory"); return d0; }
static int call_connect(struct Library *base, int fd, const struct Amitcp13BsdSockAddr *addr, int addrlen){ register int d0 __asm("d0")=fd; register const struct Amitcp13BsdSockAddr *a0 __asm("a0")=addr; register int d1 __asm("d1")=addrlen; register struct Library *a6 __asm("a6")=base; __asm volatile("jsr a6@(-54:W)" : "+r"(d0), "+r"(a0), "+r"(d1) : "r"(a6) : "a1", "cc", "memory"); return d0; }
static int call_send(struct Library *base, int fd, const void *buf, int len){ register int d0 __asm("d0")=fd; register const void *a0 __asm("a0")=buf; register int d1 __asm("d1")=len; register int d2 __asm("d2")=0; register struct Library *a6 __asm("a6")=base; __asm volatile("jsr a6@(-66:W)" : "+r"(d0), "+r"(a0), "+r"(d1), "+r"(d2) : "r"(a6) : "a1", "cc", "memory"); return d0; }
static int call_recv(struct Library *base, int fd, void *buf, int len){ register int d0 __asm("d0")=fd; register void *a0 __asm("a0")=buf; register int d1 __asm("d1")=len; register int d2 __asm("d2")=0; register struct Library *a6 __asm("a6")=base; __asm volatile("jsr a6@(-78:W)" : "+r"(d0), "+r"(a0), "+r"(d1), "+r"(d2) : "r"(a6) : "a1", "cc", "memory"); return d0; }
static int call_ioctl(struct Library *base, int fd, ULONG request, void *argp){ register int d0 __asm("d0")=fd; register ULONG d1 __asm("d1")=request; register void *a0 __asm("a0")=argp; register struct Library *a6 __asm("a6")=base; __asm volatile("jsr a6@(-114:W)" : "+r"(d0), "+r"(d1), "+r"(a0) : "r"(a6) : "a1", "cc", "memory"); return d0; }
static int call_close_socket(struct Library *base, int fd){ register int d0 __asm("d0")=fd; register struct Library *a6 __asm("a6")=base; __asm volatile("jsr a6@(-120:W)" : "+r"(d0) : "r"(a6) : "d1", "a0", "a1", "cc", "memory"); return d0; }
static int call_waitselect(struct Library *base, int nfds, struct Amitcp13BsdFdSet *readfds, struct Amitcp13BsdFdSet *writefds, const struct Amitcp13BsdTimeVal *timeout){ register int d0 __asm("d0")=nfds; register ULONG *d1 __asm("d1")=&g_wait_sigs; register struct Amitcp13BsdFdSet *a0 __asm("a0")=readfds; register struct Amitcp13BsdFdSet *a1 __asm("a1")=writefds; register struct Amitcp13BsdFdSet *a2 __asm("a2")=0; register const struct Amitcp13BsdTimeVal *a3 __asm("a3")=timeout; register struct Library *a6 __asm("a6")=base; __asm volatile("jsr a6@(-126:W)" : "+r"(d0), "+r"(d1), "+r"(a0), "+r"(a1), "+r"(a2), "+r"(a3) : "r"(a6) : "cc", "memory"); return d0; }
static int call_errno(struct Library *base){ register int d0 __asm("d0"); register struct Library *a6 __asm("a6")=base; __asm volatile("jsr a6@(-162:W)" : "=r"(d0) : "r"(a6) : "d1", "a0", "a1", "cc", "memory"); return d0; }
static struct hostent *call_gethostbyname(struct Library *base, const char *name){ register const char *a0 __asm("a0")=name; register struct Library *a6 __asm("a6")=base; register struct hostent *d0 __asm("d0"); __asm volatile("jsr a6@(-210:W)" : "=r"(d0), "+r"(a0) : "r"(a6) : "d1", "a1", "cc", "memory"); return d0; }
static int call_getsockopt(struct Library *base, int fd, int level, int optname, void *optval, int *optlen){ register int d0 __asm("d0")=fd; register int d1 __asm("d1")=level; register int d2 __asm("d2")=optname; register void *a0 __asm("a0")=optval; register int *a1 __asm("a1")=optlen; register struct Library *a6 __asm("a6")=base; __asm volatile("jsr a6@(-96:W)" : "+r"(d0), "+r"(d1), "+r"(d2), "+r"(a0), "+r"(a1) : "r"(a6) : "cc", "memory"); return d0; }
static void errset(char *err,UWORD sz,const char *s){ UWORD i; if(!err||!sz) return; for(i=0;s[i]&&i+1<sz;i++) err[i]=s[i]; err[i]=0; }
static int slen(const char *s){ int n; n=0; while(s[n]) n++; return n; }
static void add(char *d,UWORD *i,UWORD max,const char *s){ while(*s && *i+1<max) d[(*i)++]=*s++; d[*i]=0; }
static int wait_fd(int fd, int write, LONG sec){ AMITCP13_BSD_FD_ZERO(&g_rfds); AMITCP13_BSD_FD_ZERO(&g_wfds); if(write) AMITCP13_BSD_FD_SET(fd,&g_wfds); else AMITCP13_BSD_FD_SET(fd,&g_rfds); g_tv.tv_sec=sec; g_tv.tv_usec=0; g_wait_sigs=0; return call_waitselect(SocketBase,fd+1,write?0:&g_rfds,write?&g_wfds:0,&g_tv); }
static int connect_socket(const char *host, char *err, UWORD err_size){ struct hostent *he; int fd; int r; int e; he=call_gethostbyname(SocketBase,host); if(!he || !he->h_addr_list || !he->h_addr_list[0]){ errset(err,err_size,"DNS failed"); return -1; } fd=call_socket(SocketBase,AMITCP13_AF_INET,AMITCP13_SOCK_STREAM,AMITCP13_IPPROTO_TCP); if(fd<0){ errset(err,err_size,"socket failed"); return -1; } g_one=1; call_ioctl(SocketBase,fd,AMITCP13_FIONBIO,&g_one); g_addr.sin_len=sizeof(g_addr); g_addr.sin_family=AMITCP13_AF_INET; g_addr.sin_port=HTTP_PORT; g_addr.sin_addr.s_addr=*(ULONG *)he->h_addr_list[0]; r=call_connect(SocketBase,fd,(const struct Amitcp13BsdSockAddr *)&g_addr,sizeof(g_addr)); if(r<0){ e=call_errno(SocketBase); if(e!=AMITCP13_EINPROGRESS && e!=AMITCP13_EALREADY){ errset(err,err_size,"connect failed "); call_close_socket(SocketBase,fd); return -1; } r=wait_fd(fd,1,15); if(r<=0 || !AMITCP13_BSD_FD_ISSET(fd,&g_wfds)){ errset(err,err_size,"connect timeout"); call_close_socket(SocketBase,fd); return -1; } g_so_error=-1; g_so_error_len=sizeof(g_so_error); r=call_getsockopt(SocketBase,fd,AMITCP13_SOL_SOCKET,AMITCP13_SO_ERROR,&g_so_error,&g_so_error_len); if(r<0 || g_so_error!=0){ errset(err,err_size,"connect SO_ERROR"); call_close_socket(SocketBase,fd); return -1; } } return fd; }
LONG http_get_plain(const char *host,const char *path,char *out,UWORD out_size,char *err,UWORD err_size){ int fd; char req[192]; char chunk[128]; int got; int total; int hdr; UWORD i; UWORD rq; if(!SocketBase){ errset(err,err_size,"socket.library missing"); return -1; } fd=connect_socket(host,err,err_size); if(fd<0) return -1; rq=0; add(req,&rq,sizeof(req),"GET "); add(req,&rq,sizeof(req),path); add(req,&rq,sizeof(req)," HTTP/1.0\r\nHost: "); add(req,&rq,sizeof(req),host); add(req,&rq,sizeof(req),"\r\nConnection: close\r\nUser-Agent: ISSTracker13\r\n\r\n"); if(wait_fd(fd,1,8)<=0 || call_send(SocketBase,fd,req,slen(req))<0){ errset(err,err_size,"send failed"); call_close_socket(SocketBase,fd); return -1; } total=0; hdr=0; while(1){ if(wait_fd(fd,0,12)<=0){ errset(err,err_size,"receive timeout"); call_close_socket(SocketBase,fd); return -1; } got=call_recv(SocketBase,fd,chunk,sizeof(chunk)); if(got==0) break; if(got<0){ int e; e=call_errno(SocketBase); if(e==AMITCP13_EWOULDBLOCK || e==AMITCP13_EAGAIN || e==AMITCP13_EINTR) continue; errset(err,err_size,"receive failed"); call_close_socket(SocketBase,fd); return -1; } for(i=0;i<(UWORD)got;i++){ if(!hdr){ if(total>=3 && out[total-3]=='\r' && out[total-2]=='\n' && out[total-1]=='\r' && chunk[i]=='\n'){ hdr=1; total=0; } else if(total+1<out_size) out[total++]=chunk[i]; } else if(total+1<out_size) out[total++]=chunk[i]; } } out[total]=0; call_close_socket(SocketBase,fd); if(!hdr){ errset(err,err_size,"bad HTTP"); return -1; } return total; }
